name: Sync NL Data

on:
  push:
  schedule:
    - cron: "0 0 * * *"  # Elke dag om 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Vehicles.json
        run: |
          mkdir -p gameversions/nl_NL/nl_NL-Data
          curl -f -sSL https://raw.githubusercontent.com/LSS-Data/LSS-Data/refs/heads/main/nl_NL/Vehicles.json -o gameversions/nl_NL/nl_NL-Data/Vehicles.json

      - name: Download Buildings.json
        run: |
          mkdir -p gameversions/nl_NL/nl_NL-Data
          curl -f -sSL https://raw.githubusercontent.com/LSS-Data/LSS-Data/refs/heads/main/nl_NL/buildings.json -o gameversions/nl_NL/nl_NL-Data/buildings.json

      - name: Update last update timestamp
        run: |
          date -u +"%Y-%m-%dT%H:%M:%SZ" > gameversions/nl_NL/nl_NL-Data/last_update_buildings.txt

      - name: Commit if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add gameversions/nl_NL/nl_NL-Data/*
          git diff-index --quiet HEAD || git commit -m "Update Vehicles.json and Buildings.json"
          git push origin main
