name: Sync einsaetze.json

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download JSON
        run: |
          mkdir -p gameversions/nl_NL/nl_NL-Data
          curl -f -s -L http://meldkamerspel.com/einsaetze.json | jq '.' > gameversions/nl_NL/nl_NL-Data/einsaetze.json

      - name: Write last update timestamp
        run: |
          date -u +"%Y-%m-%dT%H:%M:%SZ" > gameversions/nl_NL/nl_NL-Data/last_update.txt

      - name: Commit if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add gameversions/nl_NL/nl_NL-Data/einsaetze.json
          git add gameversions/nl_NL/nl_NL-Data/last_update.txt
          git commit -m "Update einsaetze.json" || echo "Nothing to commit"
          git push origin main
