name: Update Vehicles.json

on:
  schedule:
    - cron: "0 0 * * *"  # Elke dag om 00:00 UTC
  workflow_dispatch:       # Handmatig triggeren ook mogelijk

permissions:
  contents: write

jobs:
  update-vehicles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download Vehicles.json
        run: |
          mkdir -p gameversions/nl_NL/nl_NL-Data
          curl -sSL https://raw.githubusercontent.com/LSS-Data/LSS-Data/refs/heads/main/nl_NL/Vehicles.json -o gameversions/nl_NL/nl_NL-Data/vehicles.json

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gameversions/nl_NL/nl_NL-Data/Vehicles.json
          git diff-index --quiet HEAD || git commit -m "Update Vehicles"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
